import { EVENTS } from '../events/events.constants';

export const CANVAS_EVENTS = {
  NODES_UPSERTED: EVENTS.NODES_UPSERTED,
  EDGES_UPSERTED: EVENTS.EDGES_UPSERTED,
  NODES_DELETED: EVENTS.NODES_DELETED,
  EDGES_DELETED: EVENTS.EDGES_DELETED,
} as const;
